#%RAML 1.0 Trait

headers:
        X-Cms-ClientId:
          required: true
          type: string
          example: "748375-4784584-gfjhfhg-484jh5jk"
        X-Cms-ClientSecret:
          required: true
          type: string
          example: "748375-bdshde754-75y84g-ruew7"