#%RAML 1.0 Trait
queryParameters:
  email:
    type: string
    required: false
    example: "abc@gmail.com"
  phoneNumber:
    type: string
    required: false
    example: "+919964564848"
  phoneCountry:
    type: string
    required: false
    example: "+91"
  registrationDate:
    type: string
    required: false
    example: "19-06-2021"


      